{
 "title": "JVM",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "JVM Memory Used After Last GC Bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "jvm_memory_used_after_last_gc_bytes{job=\"OTEL-Cassandra\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "JVM CPU Utilisation",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "jvm_cpu_recent_utilization_ratio{job=\"OTEL-Cassandra\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "JVM Thread Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "jvm_thread_count{job=\"OTEL-Cassandra\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "JVM Class Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "jvm_class_count{job=\"OTEL-Cassandra\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "JVM Commited Memory Bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "jvm_memory_committed_bytes{job=\"OTEL-Cassandra\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "JVM Memory Used Bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "jvm_memory_used_bytes{job=\"OTEL-Cassandra\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "JVM GC Duration Seconds",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "jvm_gc_duration_seconds_sum{job=\"OTEL-Cassandra\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}