services:
  otel:
    image: otel
    build:
      dockerfile: otel.dockerfile
    volumes:
      - "/var/log/otel:/var/log/otel"
      - "../../config/otel/otel-collector-config.yaml:/otel-lgtm/otelcol-config.yaml"
      - "../../config/otel/grafana-dashboard-jvm.json:/otel-lgtm/grafana-dashboard-jvm.json"
      - "../../config/otel/grafana-dashboards.yaml:/otel-lgtm/grafana-dashboards.yaml"
      - "../../opentelemetry-jmx-metrics.jar:/var/lib/otel/opentelemetry-jmx-metrics.jar"
      - "../../scripts/run-otelcol.sh:/otel-lgtm/run-otelcol.sh"
    network:
      - host
