{
 "title": "JVM",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  {
   "title": "JVM File Descriptors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "jvm_os_max_file_descriptors_ratio",
     "legendFormat": "Max"
    },
    {
     "expr": "jvm_os_open_file_descriptors_ratio",
     "legendFormat": "Open"
    }
   ]
  },
  {
   "title": "CPU Utilisation",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    { "expr": "jvm_os_process_cpu_load_ratio", "legendFormat": "Process" },
    { "expr": "jvm_os_cpu_load_ratio", "legendFormat": "Cumulative" },
    { "expr": "jvm_os_system_cpu_load_ratio", "legendFormat": "System" }
   ]
  },
  {
   "title": "JVM OS Free Memory Physical Ratio",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "jvm_os_free_memory_physical_ratio",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "JVM Non-Heap Used",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "expr": "jvm_memory_nonheap_used_by", "legendFormat": "Non-Heap" }
   ]
  },
  {
   "title": "JVM Non-Heap Committed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "jvm_memory_nonheap_committed_by",
     "legendFormat": "Non-Heap"
    }
   ]
  },
  {
   "title": "JVM Heap Memory Used",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "expr": "jvm_memory_heap_used_by", "legendFormat": "On-Heap" },
    { "expr": "jvm_memory_nonheap_used_by", "legendFormat": "Off-Heap" }
   ]
  },
  {
   "title": "JVM Heap Committed Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "expr": "jvm_memory_heap_committed_by", "legendFormat": "On-Heap" },
    {
     "expr": "jvm_memory_nonheap_committed_by",
     "legendFormat": "Off-Heap"
    }
   ]
  },
  {
   "title": "JVM Pool Memory Used",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "expr": "jvm_memory_pool_used_by", "legendFormat": "{{name}}" }
   ]
  },
  {
   "title": "JVM Pool Commited Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "expr": "jvm_memory_pool_committed_by", "legendFormat": "{{name}}" }
   ]
  },
  {
   "title": "JVM Class Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "targets": [
    { "expr": "jvm_classes_loaded_ratio", "legendFormat": "Loaded Classes" }
   ]
  },
  {
   "title": "JVM GC Duration Seconds",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "jvm_gc_collections_elapsed_milliseconds_total",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "JVM Thread Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "targets": [
    { "expr": "jvm_threads_count_ratio", "legendFormat": "__auto" }
   ]
  }
 ]
}