{
 "title": "Data Serializer",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "Keyspace", "query": { "query": "label_values(keyspace)" } },
   {
    "name": "Table",
    "query": {
     "query": "label_values(cassandra_serializer_data_allcolumns_50thpercentile_total{type!=\"Table\",keyspace=~\"$Keyspace\",scope=~\"$Table\"},scope)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Data - All Columns - P99",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "cassandra_serializer_data_allcolumns_99thpercentile_total{type!=\"Table\",keyspace=~\"$Keyspace\",scope=~\"$Table\", keyspace=~\"$Keyspace\", scope=~\"$Table\"}",
     "legendFormat": "{{keyspace}}::{{scope}}"
    }
   ]
  },
  {
   "title": "Data - Cell - P99",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "cassandra_serializer_data_cell_99thpercentile_total{type!=\"Table\",keyspace=~\"$Keyspace\",scope=~\"$Table\", keyspace=~\"$Keyspace\", scope=~\"$Table\"}",
     "legendFormat": "{{keyspace}}::{{scope}}"
    }
   ]
  },
  {
   "title": "Data - Column - P99",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "cassandra_serializer_data_column_99thpercentile_total{type!=\"Table\",keyspace=~\"$Keyspace\",scope=~\"$Table\"}",
     "legendFormat": "{{keyspace}}::{{scope}}"
    }
   ]
  },
  {
   "title": "Data - Column Family - P99",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "cassandra_serializer_data_cfs_99thpercentile_total{type!=\"Table\",keyspace=~\"$Keyspace\",scope=~\"$Table\"}",
     "legendFormat": "{{keyspace}}::{{scope}}"
    }
   ]
  },
  {
   "title": "Data - Column Subset - P99",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "cassandra_serializer_data_columnsubset_99thpercentile_total{type!=\"Table\",keyspace=~\"$Keyspace\",scope=~\"$Table\"}",
     "legendFormat": "{{keyspace}}::{{scope}}"
    }
   ]
  },
  {
   "title": "Data - Row - P99",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "cassandra_serializer_data_row_99thpercentile_total{type!=\"Table\",keyspace=~\"$Keyspace\",scope=~\"$Table\"}",
     "legendFormat": "{{keyspace}}::{{scope}}"
    }
   ]
  },
  {
   "title": "Data - Row Body - P99",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "cassandra_serializer_data_rowbody_99thpercentile_total{type!=\"Table\",keyspace=~\"$Keyspace\",scope=~\"$Table\"}",
     "legendFormat": "{{keyspace}}::{{scope}}"
    }
   ]
  },
  {
   "title": "Data - Clustering Key - P99",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "cassandra_serializer_data_clusteringkey_99thpercentile_total{type!=\"Table\",keyspace=~\"$Keyspace\",scope=~\"$Table\"}",
     "legendFormat": "{{keyspace}}::{{scope}}"
    }
   ]
  },
  {
   "title": "Data - Range Tombstone Marker - P99",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "cassandra_serializer_data_rangetombstonemarker_99thpercentile_total{type!=\"Table\",keyspace=~\"$Keyspace\",scope=~\"$Table\"}",
     "legendFormat": "{{keyspace}}::{{scope}}"
    }
   ]
  },
  {
   "title": "Data - Partition - P99",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "targets": [
    {
     "expr": "cassandra_serializer_data_partition_99thpercentile_total{type!=\"Table\",keyspace=~\"$Keyspace\",scope=~\"$Table\"}",
     "legendFormat": "{{keyspace}}::{{scope}}"
    }
   ]
  }
 ]
}