{
 "title": "Cassandra Scheduler 2",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "workerid",
    "label": "Worker ID",
    "query": {
     "query": "label_values(cassandra_scheduler_sepworker_assign_latency_50th_percentile_ratio,scope)"
    }
   },
   {
    "name": "sepexecutor",
    "label": "SEPExecutor",
    "query": {
     "query": "label_values(cassandra_scheduler_thread_pools_active_tasks_value_ratio,scope)"
    }
   },
   {
    "name": "cpu",
    "query": {
     "query": "label_values(system_cpu_utilization_ratio,cpu)"
    }
   },
   {
    "name": "cpu_count",
    "query": {
     "query": "query_result(count(count by (cpu) (system_cpu_utilization_ratio{cpu=~\"$cpu\"})))"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "CPU Utilisation",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by(state) (system_cpu_utilization_ratio{cpu=~\"$cpu\"}) / $cpu_count",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "SEPWorker Stage",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "cassandra_scheduler_sepworker_executor_ordinal_value_ratio{scope=~\"$workerid\"}",
     "legendFormat": "{{scope}}"
    }
   ]
  },
  {
   "title": "SharedExecutorPool Schedule Latency 95th",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "cassandra_scheduler_shared_executor_pool_schedule_latency_95th_percentile_ratio",
     "legendFormat": "schedule"
    }
   ]
  },
  {
   "title": "SEPWorker Work",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "cassandra_scheduler_sepworker_work_state_ordinal_value_ratio{scope=~\"$workerid\"}",
     "legendFormat": "{{scope}}"
    }
   ]
  },
  {
   "title": "SharedExecutorPool Maybe Start Spinning Worker Latency 95th",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "cassandra_scheduler_shared_executor_pool_maybe_start_spinning_worker_latency_95th_percentile_ratio",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "SEPWorker Task Run Latency 95th",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "cassandra_scheduler_sepworker_task_run_latency_95th_percentile_ratio{scope=~\"$workerid\"}",
     "legendFormat": "{{scope}}"
    },
    {
     "expr": "avg by(threadgroup) (cassandra_scheduler_sepworker_task_run_latency_95th_percentile_ratio{scope=~\"$workerid\"})",
     "legendFormat": "Average"
    }
   ]
  },
  {
   "title": "SharedExecutorPool Workers",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "cassandra_scheduler_shared_executor_pool_executors_count_ratio",
     "legendFormat": "Active"
    },
    {
     "expr": "cassandra_scheduler_shared_executor_pool_spinning_workers_count_ratio",
     "legendFormat": "Spinning"
    },
    {
     "expr": "cassandra_scheduler_shared_executor_pool_descheduled_workers_count_ratio",
     "legendFormat": "Descheduled"
    },
    {}
   ]
  },
  {
   "title": "SEPWorker Park Latency 95th",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "cassandra_scheduler_sepworker_park_latency_95th_percentile_ratio{scope=~\"$workerid\"}",
     "legendFormat": "{{scope}}"
    },
    {
     "expr": "avg by(threadgroup) (cassandra_scheduler_sepworker_park_latency_95th_percentile_ratio{scope=~\"$workerid\"})",
     "legendFormat": "Average"
    }
   ]
  },
  {
   "title": "SEPExecutor Oldest Task Queue Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "cassandra_scheduler_thread_pools_oldest_task_queue_time_value_ratio{scope=~\"$sepexecutor\"}",
     "legendFormat": "{{scope}}"
    }
   ]
  },
  {
   "title": "SEPWorker Stop Latency 95th",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "cassandra_scheduler_sepworker_stop_latency_95th_percentile_ratio{scope=~\"$workerid\"}",
     "legendFormat": "{{scope}}"
    },
    {
     "expr": "avg by(threadgroup) (cassandra_scheduler_sepworker_stop_latency_95th_percentile_ratio{scope=~\"$workerid\"})",
     "legendFormat": "Average"
    }
   ]
  },
  {
   "title": "SEPExecutor Pending Tasks (Un-taken task permits)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "cassandra_scheduler_thread_pools_pending_tasks_value_ratio{scope=~\"$sepexecutor\"}",
     "legendFormat": "{{scope}}"
    }
   ]
  },
  {
   "title": "SEPWorker Self Assign Latency 95th",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "cassandra_scheduler_sepworker_self_assign_latency_95th_percentile_ratio{scope=~\"$workerid\"}",
     "legendFormat": "{{scope}}"
    },
    {
     "expr": "avg by(threadgroup) (cassandra_scheduler_sepworker_self_assign_latency_95th_percentile_ratio{scope=~\"$workerid\"})",
     "legendFormat": "Average"
    }
   ]
  },
  {
   "title": "SEPExecutor Active Tasks",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "targets": [
    {
     "expr": "cassandra_scheduler_thread_pools_active_tasks_value_ratio{scope=~\"$sepexecutor\"}",
     "legendFormat": "{{scope}}"
    }
   ]
  },
  {
   "title": "SEP Worker Assign Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "cassandra_scheduler_sepworker_assign_latency_95th_percentile_ratio{scope=~\"$workerid\"}",
     "legendFormat": "{{scope}}"
    },
    {
     "expr": "avg by(threadgroup) (cassandra_scheduler_sepworker_assign_latency_95th_percentile_ratio{scope=~\"$workerid\"})",
     "legendFormat": "Average"
    }
   ]
  },
  {
   "title": "SEPExecutor Take Work Permit Latency 95th",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "cassandra_scheduler_thread_pools_take_work_permit_latency_95th_percentile_ratio{scope=~\"$sepexecutor\"}",
     "legendFormat": "{{scope}}"
    }
   ]
  },
  {
   "title": "SEPWorker Wait Spin Latency 95th",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "cassandra_scheduler_sepworker_wait_spin_latency_95th_percentile_ratio{scope=~\"$workerid\"}",
     "legendFormat": "{{scope}}"
    },
    {
     "expr": "avg by(threadgroup) (cassandra_scheduler_sepworker_wait_spin_latency_95th_percentile_ratio{scope=~\"$workerid\"})",
     "legendFormat": "Average"
    }
   ]
  },
  {
   "title": "SEPExecutor Maybe Execute Immediately Latency 95th",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "cassandra_scheduler_thread_pools_maybe_execute_immediately_latency_95th_percentile_ratio{scope=~\"$sepexecutor\"}",
     "legendFormat": "{{scope}}"
    }
   ]
  },
  {
   "title": "Executor Take Task Permit Latency 95th",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "cassandra_scheduler_thread_pools_take_task_permit_latency_95th_percentile_ratio{scope=~\"$sepexecutor\"}",
     "legendFormat": "{{scope}}"
    }
   ]
  },
  {
   "title": "SEPExecutor Return Work Permit latency 95th",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 80 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "cassandra_scheduler_thread_pools_return_work_permit_latency_95th_percentile_ratio{scope=~\"$sepexecutor\"}",
     "legendFormat": "{{scope}}"
    }
   ]
  }
 ]
}