receivers:
  hostmetrics:
    root_path: /hostfs
    collection_interval: 10s
    scrapers:
      cpu:
      disk:
      filesystem:
      load:
      memory:
      network:
      paging:
  docker_stats:
    endpoint: <DOCKER HOST>
    api_version: 1.45
    metrics:
      container.memory.active_anon:
        enabled: true
      container.memory.inactive_anon:
        enabled: true
      container.memory.active_file:
        enabled: true
      container.memory.inactive_file:
        enabled: true
      container.memory.anon:
        enabled: true
      container.memory.fails:
        enabled: true
      container.memory.pgfault:
        enabled: true
      container.memory.pgmajfault:
        enabled: true
      container.memory.unevictable:
        enabled: true
      container.pids.count:
        enabled: true
      container.pids.limit:
        enabled: true

processors:
  resourcedetection:
    detectors: ["env","system"]
    system:
      hostname_sources: ["os"]
  batch:

exporters:
  otlphttp:
    endpoint: http://<COLLECTOR>:4318

service:
  pipelines:
    metrics:
      receivers:
      - hostmetrics
      processors:
      - batch
      - resourcedetection
      exporters:
      - otlphttp
