receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
        max_recv_msg_size_mib: 100
        # max_concurrent_streams: 200
      http:
        endpoint: 0.0.0.0:4318
  prometheus/collector:
    config:
      scrape_configs:
        - job_name: 'opentelemetry-collector'
          static_configs:
            - targets: ['localhost:8888']
  # jmx:
  #   jar_path: /var/lib/otel/opentelemetry-jmx-metrics.jar
  #   endpoint: cassandra:7199
  #   target_system: cassandra,jvm
  #   collection_interval: 10s
  #   resource_attributes:
  #     endpoint: cassandra:7199
  hostmetrics:
    collection_interval: 10s
    scrapers:
      cpu:
      disk:
      filesystem:
      load:
      memory:
      network:
      paging:

processors:
  resourcedetection:
    detectors: ["env","system"]
    system:
      hostname_sources: ["os"]
  batch:

exporters:
  prometheusremotewrite:
    endpoint: http://localhost:9090/api/v1/write
    add_metric_suffixes: true
  otlphttp:
    endpoint: http://localhost:4318
  loki:
    endpoint: http://localhost:3100/loki/api/v1/push
  debug/metrics:
    verbosity: detailed
  debug/traces:
    verbosity: detailed
  debug/logs:
    verbosity: detailed
  file/metrics:
    path: /var/log/otel/metrics.log
  file/traces:
    path: /var/log/otel/traces.log
  file/logs:
    path: /var/log/otel/logs.log

service:
  pipelines:
    traces:
      receivers:
      - otlp
      processors:
      - batch
      #exporters: [otlphttp]
      exporters:
      - otlphttp
      - debug/traces
      - file/traces
    metrics:
      receivers:
      - otlp
      - prometheus/collector
      # - jmx
      processors:
      - batch
      - resourcedetection
      # - resourceattributetransposer
      # - resource
      #exporters: [prometheusremotewrite]
      exporters:
      - prometheusremotewrite
      - debug/metrics
      - file/metrics
    logs:
      receivers:
      - otlp
      processors:
      - batch
      #exporters: [loki]
      exporters:
      - loki
      - debug/logs
      - file/logs
