services:
  cassandra:
    container_name: cassandra
    image: ghcr.io/engineersbox/cassandra:5.0
    volumes:
      - "./log:/var/log/cassandra" 
      - "./config/otel/otel-instance.properties:/etc/otel/otel.properties" 
      - "./config/cassandra:/etc/cassandra" 
      - "./config/cassandra/cassandra.yaml:/etc/cassandra/cassandra.yaml" 
      - "/mnt/nvme/cassandra_data:/var/lib/cassandra/data" 
    ports:
      - 7000:7000
      - 7001:7001
      - 7199:7199
      - 9042:9042
      - 9160:9160
  otel-kernel:
    container_name: otel-kernel
    image: opentelemetry-ebpf-kernel-collector:v0.10.2
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock 
      - /sys/fs/cgroup:/hostfs/sys/fs/cgroup 
      - /etc:/hostfs/etc 
      - /var/cache:/hostfs/cache 
      - /usr/src:/hostfs/usr/src 
      - /lib/modules:/hostfs/lib/modules 
    network: host
    pid: host
    privileged: true

