services:
  cassandra:
    container_name: cassandra
    image: ghcr.io/engineersbox/cassandra:5.0-metrics
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - "/var/log/cassandra:/var/log/cassandra" 
      - "../../config/otel/otel-instance.properties:/etc/otel/otel.properties" 
      - "../../config/cassandra:/etc/cassandra" 
      - "../../config/cassandra/cassandra.yaml:/etc/cassandra/cassandra.yaml" 
      - "/mnt/nvme/cassandra_data:/var/lib/cassandra/data" 
    mem_limit: 16gb
    memswap_limit: 16gb
    mem_swappiness: 0
    ports:
      - 7000:7000
      - 7001:7001
      - 7199:7199
      - 9042:9042
      - 9160:9160
    env_file:
      - path: /var/lib/node_env
        required: true
  otel-hostmetrics:
    container_name: otel-hostmetrics
    image: otel/opentelemetry-collector-contrib:0.101.0
    volumes:
      - "/var/log/otel_hostmetricslog:/var/log/otel"
      - "../../config/otel/otel-instance-config.yaml:/etc/otelcol-contrib/config.yaml"
      - /var/run/docker.sock:/var/run/docker.sock 
      - /sys/fs/cgroup:/hostfs/sys/fs/cgroup 
      - /etc:/hostfs/etc 
      - /etc:/etc
      - /var/cache:/hostfs/cache 
      - /usr/src:/hostfs/usr/src 
      - /lib/modules:/hostfs/lib/modules 
      - /boot:/boot
      - /snap:/snap
      - /mnt:/mnt
      - /:/hostfs
      - /proc:/hostfs/proc
    env_file:
      - path: /var/lib/node_env
        required: true
    network_mode: host
    pid: host
    privileged: true
  otel-kernel:
    container_name: otel-kernel
    image: otel/opentelemetry-ebpf-kernel-collector:v0.10.2
    command: ["--log-console"]
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock 
      - /sys/fs/cgroup:/hostfs/sys/fs/cgroup 
      - /etc:/hostfs/etc 
      - /var/cache:/hostfs/cache 
      - /usr/src:/hostfs/usr/src 
      - /lib/modules:/hostfs/lib/modules 
    env_file:
      - path: /var/lib/node_env
        required: true
    network_mode: host
    pid: host
    privileged: true

